/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardSurveysRouteImport } from './routes/dashboard.surveys'
import { Route as DashboardMoodRouteImport } from './routes/dashboard.mood'
import { Route as DashboardJournalRouteImport } from './routes/dashboard.journal'
import { Route as DashboardChatbotRouteImport } from './routes/dashboard.chatbot'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin/surveys/index'
import { Route as AdminSurveysCreateRouteImport } from './routes/admin/surveys/create'

const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSurveysRoute = DashboardSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMoodRoute = DashboardMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJournalRoute = DashboardJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatbotRoute = DashboardChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => DashboardRoute,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/admin/__layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/admin/surveys/',
  path: '/admin/surveys/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSurveysCreateRoute = AdminSurveysCreateRouteImport.update({
  id: '/admin/surveys/create',
  path: '/admin/surveys/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/insights': typeof InsightsRoute
  '/admin': typeof Admin_layoutRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/mood': typeof DashboardMoodRoute
  '/dashboard/surveys': typeof DashboardSurveysRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/surveys/create': typeof AdminSurveysCreateRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/mood': typeof DashboardMoodRoute
  '/dashboard/surveys': typeof DashboardSurveysRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/surveys/create': typeof AdminSurveysCreateRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/insights': typeof InsightsRoute
  '/admin/__layout': typeof Admin_layoutRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/journal': typeof DashboardJournalRoute
  '/dashboard/mood': typeof DashboardMoodRoute
  '/dashboard/surveys': typeof DashboardSurveysRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/surveys/create': typeof AdminSurveysCreateRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/insights'
    | '/admin'
    | '/dashboard/chatbot'
    | '/dashboard/journal'
    | '/dashboard/mood'
    | '/dashboard/surveys'
    | '/admin/'
    | '/dashboard/'
    | '/admin/surveys/create'
    | '/admin/surveys/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/insights'
    | '/admin'
    | '/dashboard/chatbot'
    | '/dashboard/journal'
    | '/dashboard/mood'
    | '/dashboard/surveys'
    | '/dashboard'
    | '/admin/surveys/create'
    | '/admin/surveys'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/insights'
    | '/admin/__layout'
    | '/dashboard/chatbot'
    | '/dashboard/journal'
    | '/dashboard/mood'
    | '/dashboard/surveys'
    | '/admin/'
    | '/dashboard/'
    | '/admin/surveys/create'
    | '/admin/surveys/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  Admin_layoutRoute: typeof Admin_layoutRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSurveysCreateRoute: typeof AdminSurveysCreateRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/surveys': {
      id: '/dashboard/surveys'
      path: '/surveys'
      fullPath: '/dashboard/surveys'
      preLoaderRoute: typeof DashboardSurveysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mood': {
      id: '/dashboard/mood'
      path: '/mood'
      fullPath: '/dashboard/mood'
      preLoaderRoute: typeof DashboardMoodRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journal': {
      id: '/dashboard/journal'
      path: '/journal'
      fullPath: '/dashboard/journal'
      preLoaderRoute: typeof DashboardJournalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chatbot': {
      id: '/dashboard/chatbot'
      path: '/chatbot'
      fullPath: '/dashboard/chatbot'
      preLoaderRoute: typeof DashboardChatbotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/admin/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/surveys/create': {
      id: '/admin/surveys/create'
      path: '/admin/surveys/create'
      fullPath: '/admin/surveys/create'
      preLoaderRoute: typeof AdminSurveysCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatbotRoute: typeof DashboardChatbotRoute
  DashboardJournalRoute: typeof DashboardJournalRoute
  DashboardMoodRoute: typeof DashboardMoodRoute
  DashboardSurveysRoute: typeof DashboardSurveysRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatbotRoute: DashboardChatbotRoute,
  DashboardJournalRoute: DashboardJournalRoute,
  DashboardMoodRoute: DashboardMoodRoute,
  DashboardSurveysRoute: DashboardSurveysRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InsightsRoute: InsightsRoute,
  Admin_layoutRoute: Admin_layoutRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSurveysCreateRoute: AdminSurveysCreateRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
